// Întrebări CyberXscore - configurația bilingvă canonică
import { Question } from './engine';

export const questions: Question[] = [
  // MATURITATE - Politici și Procese
  {
    id: 'Q1',
    code: 'Q1',
    domain: 'maturity',
    category: 'maturity.policies_processes',
    answerType: 'scale',
    text: {
      ro: 'Există o politică de securitate IT/cyber formalizată și comunicată intern?',
      en: 'Is there a formalized IT/cybersecurity policy that is communicated internally?',
    },
    weightPoints: 3,
    order: 1,
  },
  {
    id: 'Q2',
    code: 'Q2',
    domain: 'maturity',
    category: 'maturity.governance_ownership',
    answerType: 'yes_no',
    text: {
      ro: 'Rolurile și responsabilitățile legate de securitate IT sunt clar definite (decizie / implementare / răspuns)?',
      en: 'Are IT security roles and responsibilities clearly defined (decision / implementation / response)?',
    },
    weightPoints: 4,
    order: 2,
  },
  {
    id: 'Q3',
    code: 'Q3',
    domain: 'maturity',
    category: 'maturity.governance_ownership',
    answerType: 'scale',
    text: {
      ro: 'Managementul este informat periodic despre riscurile de securitate și nivelul de expunere?',
      en: 'Is management periodically informed about security risks and the level of exposure?',
    },
    weightPoints: 3,
    order: 3,
  },
  {
    id: 'Q4',
    code: 'Q4',
    domain: 'maturity',
    category: 'maturity.continuous_improvement',
    answerType: 'yes_no',
    text: {
      ro: 'Politicile de securitate sunt revizuite cel puțin anual sau la schimbări majore?',
      en: 'Are security policies reviewed at least annually or after major changes?',
    },
    weightPoints: 2,
    order: 4,
  },
  {
    id: 'Q5',
    code: 'Q5',
    domain: 'maturity',
    category: 'maturity.policies_processes',
    answerType: 'yes_no',
    text: {
      ro: 'Există reguli documentate de utilizare acceptabilă a sistemelor IT (email, internet, dispozitive)?',
      en: 'Are there documented acceptable-use rules for IT systems (email, internet, devices)?',
    },
    weightPoints: 2,
    order: 5,
  },
  {
    id: 'Q6',
    code: 'Q6',
    domain: 'maturity',
    category: 'maturity.continuous_improvement',
    answerType: 'scale',
    text: {
      ro: 'Există o evaluare internă periodică a riscurilor de securitate (chiar și informală) care duce la acțiuni prioritizate?',
      en: 'Is there a periodic internal security risk assessment (even informal) that leads to prioritized actions?',
    },
    weightPoints: 3,
    order: 6,
  },
  {
    id: 'Q7',
    code: 'Q7',
    domain: 'maturity',
    category: 'maturity.governance_ownership',
    answerType: 'yes_no',
    text: {
      ro: 'Există o persoană clar responsabilă pentru securitatea cibernetică (chiar dacă part-time)?',
      en: 'Is there a clearly responsible person for cybersecurity (even part-time)?',
    },
    weightPoints: 3,
    order: 7,
  },
  {
    id: 'Q8',
    code: 'Q8',
    domain: 'maturity',
    category: 'maturity.governance_ownership',
    answerType: 'yes_no',
    text: {
      ro: 'Bugetul pentru securitate IT este planificat separat sau inclus explicit în bugetul IT?',
      en: 'Is the IT security budget planned separately or explicitly included in the IT budget?',
    },
    weightPoints: 0, // informativ
    order: 8,
  },
  // RISC - IAM
  {
    id: 'Q9',
    code: 'Q9',
    domain: 'risk',
    category: 'risk.iam',
    answerType: 'yes_no',
    text: {
      ro: 'Fiecare utilizator are cont individual (fără conturi partajate)?',
      en: 'Does each user have an individual account (no shared accounts)?',
    },
    weightPoints: 2,
    order: 9,
  },
  {
    id: 'Q10',
    code: 'Q10',
    domain: 'risk',
    category: 'risk.iam',
    answerType: 'scale',
    text: {
      ro: 'Accesul utilizatorilor este limitat strict la ce au nevoie pentru rolul lor?',
      en: 'Is user access strictly limited to what is needed for their role?',
    },
    weightPoints: 3,
    order: 10,
  },
  {
    id: 'Q11',
    code: 'Q11',
    domain: 'risk',
    category: 'risk.iam',
    answerType: 'yes_no',
    text: {
      ro: 'Conturile cu privilegii administrative au MFA activat?',
      en: 'Do administrative privileged accounts have MFA enabled?',
    },
    weightPoints: 5,
    order: 11,
  },
  {
    id: 'Q12',
    code: 'Q12',
    domain: 'maturity',
    category: 'maturity.policies_processes',
    answerType: 'scale',
    text: {
      ro: 'Există un proces clar de creare, modificare și dezactivare a conturilor (onboarding/offboarding)?',
      en: 'Is there a clear process to create, modify, and disable accounts (onboarding/offboarding)?',
    },
    weightPoints: 3,
    order: 12,
  },
  {
    id: 'Q13',
    code: 'Q13',
    domain: 'risk',
    category: 'risk.iam',
    answerType: 'yes_no',
    text: {
      ro: 'Conturile inactive sunt identificate și dezactivate periodic?',
      en: 'Are inactive accounts periodically identified and disabled?',
    },
    weightPoints: 2,
    order: 13,
  },
  {
    id: 'Q14',
    code: 'Q14',
    domain: 'risk',
    category: 'risk.iam',
    answerType: 'yes_no',
    text: {
      ro: 'Există reguli minime pentru parole (lungime, reutilizare) aplicate utilizatorilor?',
      en: 'Are minimum password rules enforced for users (length, reuse)?',
    },
    weightPoints: 1,
    order: 14,
  },
  {
    id: 'Q15',
    code: 'Q15',
    domain: 'risk',
    category: 'risk.iam',
    answerType: 'yes_no',
    text: {
      ro: 'Există un inventar clar al conturilor privilegiate (admin, service accounts)?',
      en: 'Is there a clear inventory of privileged accounts (admin, service accounts)?',
    },
    weightPoints: 2,
    order: 15,
  },
  {
    id: 'Q16',
    code: 'Q16',
    domain: 'risk',
    category: 'risk.iam',
    answerType: 'scale',
    text: {
      ro: 'Service accounts sunt limitate ca drepturi și nu folosesc parole comune?',
      en: 'Are service accounts limited in privileges and not using shared/common passwords?',
    },
    weightPoints: 0, // punctat doar când este relevant
    order: 16,
    scoringInclusionRule: 'G2 == yes',
  },
  // RISC - Rețea și Externă
  {
    id: 'Q17',
    code: 'Q17',
    domain: 'risk',
    category: 'risk.network_external',
    answerType: 'yes_no',
    text: {
      ro: 'Există un firewall configurat activ între rețeaua internă și Internet?',
      en: 'Is there an actively configured firewall between the internal network and the Internet?',
    },
    weightPoints: 4,
    order: 17,
  },
  {
    id: 'Q18',
    code: 'Q18',
    domain: 'risk',
    category: 'risk.network_external',
    answerType: 'scale',
    text: {
      ro: 'Rețeaua este segmentată (ex: producție, birou, servere) pentru a limita propagarea incidentelor?',
      en: 'Is the network segmented (e.g., production, office, servers) to limit incident spread?',
    },
    weightPoints: 2,
    order: 18,
  },
  {
    id: 'Q19',
    code: 'Q19',
    domain: 'risk',
    category: 'risk.network_external',
    answerType: 'yes_no',
    text: {
      ro: 'Există un VLAN separat pentru guest / Wi-Fi vizitatori?',
      en: 'Is there a separate VLAN for guest / visitor Wi-Fi?',
    },
    weightPoints: 1,
    order: 19,
  },
  {
    id: 'Q20',
    code: 'Q20',
    domain: 'risk',
    category: 'risk.network_external',
    answerType: 'multiple_choice',
    text: {
      ro: 'Există servicii expuse din rețeaua internă direct în Internet?',
      en: 'Are there services exposed directly from the internal network to the Internet?',
    },
    options: [
      { value: 'none', label: { ro: 'Nu există', en: 'None' }, score: 1.0 },
      { value: 'few', label: { ro: 'Puține', en: 'Few' }, score: 0.6 },
      { value: 'many', label: { ro: 'Multe', en: 'Many' }, score: 0.3 },
      { value: 'dont_know', label: { ro: 'Nu știu', en: "Don't know" }, score: 0.0 },
    ],
    weightPoints: 0, // diagnostic
    order: 20,
  },
  {
    id: 'Q21',
    code: 'Q21',
    domain: 'risk',
    category: 'risk.network_external',
    answerType: 'yes_no',
    text: {
      ro: 'Accesul remote (VPN/RDP) este protejat cu MFA?',
      en: 'Is remote access (VPN/RDP) protected with MFA?',
    },
    weightPoints: 3,
    order: 21,
  },
  {
    id: 'Q22',
    code: 'Q22',
    domain: 'risk',
    category: 'risk.network_external',
    answerType: 'scale',
    text: {
      ro: 'Regulile de firewall sunt revizuite periodic și eliminate cele neutilizate?',
      en: 'Are firewall rules periodically reviewed and unused ones removed?',
    },
    weightPoints: 0, // punctat când G4 != none
    order: 22,
    scoringInclusionRule: 'G4 != none',
  },
  {
    id: 'Q23',
    code: 'Q23',
    domain: 'risk',
    category: 'risk.network_external',
    answerType: 'yes_no',
    text: {
      ro: 'Porturile și protocoalele deschise sunt documentate și justificate?',
      en: 'Are open ports and protocols documented and justified?',
    },
    weightPoints: 0, // punctat când G4 != none
    order: 23,
    scoringInclusionRule: 'G4 != none',
  },
  {
    id: 'Q24',
    code: 'Q24',
    domain: 'risk',
    category: 'risk.network_external',
    answerType: 'yes_no',
    text: {
      ro: 'Rețeaua Wi-Fi folosește criptare modernă (WPA2/WPA3) și parole administrative puternice?',
      en: 'Does Wi-Fi use modern encryption (WPA2/WPA3) and strong admin passwords?',
    },
    weightPoints: 0, // dependent de context
    order: 24,
  },
  // RISC - Endpoint și Dispozitive
  {
    id: 'Q25',
    code: 'Q25',
    domain: 'risk',
    category: 'risk.endpoint_device',
    answerType: 'scale',
    text: {
      ro: 'Toate stațiile și serverele au soluție de protecție endpoint (AV/EDR) activă?',
      en: 'Do all workstations and servers have active endpoint protection (AV/EDR)?',
    },
    weightPoints: 5,
    order: 25,
  },
  {
    id: 'Q26',
    code: 'Q26',
    domain: 'risk',
    category: 'risk.endpoint_device',
    answerType: 'scale',
    text: {
      ro: 'Actualizările de sistem și aplicații sunt aplicate regulat?',
      en: 'Are OS and application updates applied regularly?',
    },
    weightPoints: 4,
    order: 26,
  },
  {
    id: 'Q27',
    code: 'Q27',
    domain: 'risk',
    category: 'risk.endpoint_device',
    answerType: 'scale',
    text: {
      ro: 'Dispozitivele mobile/laptopurile sunt protejate prin parolă/PIN și criptare?',
      en: 'Are laptops/mobile devices protected by password/PIN and encryption?',
    },
    weightPoints: 1,
    order: 27,
  },
  {
    id: 'Q28',
    code: 'Q28',
    domain: 'risk',
    category: 'risk.endpoint_device',
    answerType: 'multiple_choice',
    text: {
      ro: 'Dispozitivele personale (BYOD) sunt controlate sau restricționate?',
      en: 'Are personal devices (BYOD) controlled or restricted?',
    },
    options: [
      { value: 'not_allowed', label: { ro: 'Nu sunt permise', en: 'Not allowed' }, score: 1.0 },
      { value: 'allowed_with_controls', label: { ro: 'Permise cu controale', en: 'Allowed with controls' }, score: 0.6 },
      { value: 'fully_unmanaged', label: { ro: 'Complet negestionate', en: 'Fully unmanaged' }, score: 0.0 },
    ],
    weightPoints: 1,
    order: 28,
  },
  {
    id: 'Q29',
    code: 'Q29',
    domain: 'maturity',
    category: 'maturity.asset_visibility',
    answerType: 'yes_no',
    text: {
      ro: 'Există o evidență a dispozitivelor IT utilizate în companie?',
      en: 'Is there an inventory of IT devices used in the company?',
    },
    weightPoints: 6,
    order: 29,
  },
  {
    id: 'Q30',
    code: 'Q30',
    domain: 'risk',
    category: 'risk.endpoint_device',
    answerType: 'yes_no',
    text: {
      ro: 'Utilizatorii NU au drepturi locale de administrator pe stațiile de lucru?',
      en: 'Do users NOT have local administrator rights on workstations?',
    },
    weightPoints: 1,
    order: 30,
  },
  {
    id: 'Q31',
    code: 'Q31',
    domain: 'risk',
    category: 'risk.endpoint_device',
    answerType: 'yes_no',
    text: {
      ro: 'Dispozitivele pierdute sau furate pot fi blocate sau șterse remote?',
      en: 'Can lost or stolen devices be remotely locked or wiped?',
    },
    weightPoints: 0, // punctat când G5=YES
    order: 31,
    scoringInclusionRule: 'G5 == yes',
  },
  {
    id: 'Q32',
    code: 'Q32',
    domain: 'risk',
    category: 'risk.endpoint_device',
    answerType: 'scale',
    text: {
      ro: 'Software-ul neautorizat este blocat sau monitorizat?',
      en: 'Is unauthorized software blocked or monitored?',
    },
    weightPoints: 0, // punctat când G2=YES sau G6=YES
    order: 32,
    scoringInclusionRule: 'G2 == yes || G6 == yes',
  },
  // RISC - Backup și Ransomware
  {
    id: 'Q33',
    code: 'Q33',
    domain: 'risk',
    category: 'risk.backup_ransomware',
    answerType: 'yes_no',
    text: {
      ro: 'Există backup regulat pentru datele critice?',
      en: 'Is there regular backup for critical data?',
    },
    weightPoints: 5,
    order: 33,
  },
  {
    id: 'Q34',
    code: 'Q34',
    domain: 'risk',
    category: 'risk.backup_ransomware',
    answerType: 'yes_no',
    text: {
      ro: 'Backup-urile sunt stocate separat față de sistemele de producție (offsite/cloud/izolat)?',
      en: 'Are backups stored separately from production systems (offsite/cloud/isolated)?',
    },
    weightPoints: 3,
    order: 34,
  },
  {
    id: 'Q35',
    code: 'Q35',
    domain: 'risk',
    category: 'risk.backup_ransomware',
    answerType: 'scale',
    text: {
      ro: 'Sunt efectuate periodic teste de restaurare a backup-urilor?',
      en: 'Are backup restore testing performed periodically?',
    },
    weightPoints: 2,
    order: 35,
  },
  {
    id: 'Q36',
    code: 'Q36',
    domain: 'risk',
    category: 'risk.backup_ransomware',
    answerType: 'yes_no',
    text: {
      ro: 'Există obiective clare RTO/RPO pentru sistemele critice?',
      en: 'Are there clear RTO/RPO objectives for critical systems?',
    },
    weightPoints: 1,
    order: 36,
  },
  {
    id: 'Q37',
    code: 'Q37',
    domain: 'maturity',
    category: 'maturity.policies_processes',
    answerType: 'yes_no',
    text: {
      ro: 'Responsabilitățile pentru backup și recovery sunt clar stabilite?',
      en: 'Are responsibilities for backup and recovery clearly assigned?',
    },
    weightPoints: 2,
    order: 37,
  },
  {
    id: 'Q38',
    code: 'Q38',
    domain: 'risk',
    category: 'risk.backup_ransomware',
    answerType: 'yes_no',
    text: {
      ro: 'Backup-urile sunt protejate împotriva ștergerii sau criptării (immutability sau echivalent)?',
      en: 'Are backups protected against deletion or encryption (immutability or equivalent)?',
    },
    weightPoints: 2,
    order: 38,
  },
  {
    id: 'Q39',
    code: 'Q39',
    domain: 'risk',
    category: 'risk.backup_ransomware',
    answerType: 'yes_no',
    text: {
      ro: 'Sistemele critice pot fi restaurate fără a depinde de rețeaua internă potențial compromisă?',
      en: 'Can critical systems be restored without depending on a potentially compromised internal network?',
    },
    weightPoints: 0, // punctat când G13=YES
    order: 39,
    scoringInclusionRule: 'G13 == yes',
  },
  // RISC - Monitorizare și Incidente
  {
    id: 'Q40',
    code: 'Q40',
    domain: 'risk',
    category: 'risk.monitoring_incident',
    answerType: 'scale',
    text: {
      ro: 'Există monitorizare de bază a log-urilor sau alertelor de securitate pentru sisteme/servicii critice?',
      en: 'Is there basic monitoring of logs or security alerts for critical systems/services?',
    },
    weightPoints: 3,
    order: 40,
  },
  {
    id: 'Q41',
    code: 'Q41',
    domain: 'risk',
    category: 'risk.monitoring_incident',
    answerType: 'yes_no',
    text: {
      ro: 'Există un plan simplu de răspuns la incidente (chiar și lightweight) pe care echipa îl cunoaște?',
      en: 'Is there a simple incident response plan (even lightweight) known by the team?',
    },
    weightPoints: 1,
    order: 41,
  },
  {
    id: 'Q42',
    code: 'Q42',
    domain: 'maturity',
    category: 'maturity.policies_processes',
    answerType: 'yes_no',
    text: {
      ro: 'Este clar cine trebuie notificat intern în caz de incident de securitate?',
      en: 'Is it clear who must be notified internally in case of a security incident?',
    },
    weightPoints: 1,
    order: 42,
  },
  {
    id: 'Q43',
    code: 'Q43',
    domain: 'maturity',
    category: 'maturity.continuous_improvement',
    answerType: 'scale',
    text: {
      ro: 'Incidentele sunt documentate și analizate post-incident (lessons learned)?',
      en: 'Are incidents documented and analyzed post-incident (lessons learned)?',
    },
    weightPoints: 3,
    order: 43,
  },
  {
    id: 'Q44',
    code: 'Q44',
    domain: 'maturity',
    category: 'maturity.continuous_improvement',
    answerType: 'yes_no',
    text: {
      ro: 'Sunt testate ocazional scenarii de incident (tabletop/exerciții simple)?',
      en: 'Are incident scenarios occasionally tested (tabletop/simple exercises)?',
    },
    weightPoints: 0, // informativ
    order: 44,
  },
  {
    id: 'Q45',
    code: 'Q45',
    domain: 'maturity',
    category: 'maturity.policies_processes',
    answerType: 'yes_no',
    text: {
      ro: 'Există o listă de contacte de urgență (intern + MSP/furnizori cheie) actualizată?',
      en: 'Is there an up-to-date emergency contact list (internal + MSP/key vendors)?',
    },
    weightPoints: 1,
    order: 45,
  },
  {
    id: 'Q46',
    code: 'Q46',
    domain: 'risk',
    category: 'risk.monitoring_incident',
    answerType: 'scale',
    text: {
      ro: 'Evenimentele critice generează alerte în timp util către IT (sau MSP)?',
      en: 'Do critical events generate timely alerts to IT (or MSP)?',
    },
    weightPoints: 2,
    order: 46,
  },
  // MATURITATE - Conștientizare și Factor Uman
  {
    id: 'Q47',
    code: 'Q47',
    domain: 'maturity',
    category: 'maturity.awareness_human',
    answerType: 'scale',
    text: {
      ro: 'Angajații primesc instruire de bază privind securitatea cibernetică?',
      en: 'Do employees receive basic cybersecurity training?',
    },
    weightPoints: 4,
    order: 47,
  },
  {
    id: 'Q48',
    code: 'Q48',
    domain: 'maturity',
    category: 'maturity.awareness_human',
    answerType: 'yes_no',
    text: {
      ro: 'Angajații știu cum să raporteze un email suspect sau incident?',
      en: 'Do employees know how to report a suspicious email or incident?',
    },
    weightPoints: 2,
    order: 48,
  },
  {
    id: 'Q49',
    code: 'Q49',
    domain: 'maturity',
    category: 'maturity.awareness_human',
    answerType: 'yes_no',
    text: {
      ro: 'Există reguli clare privind parolele pentru utilizatori (comunicate, nu doar tehnice)?',
      en: 'Are there clear password rules for users (communicated, not only technical)?',
    },
    weightPoints: 1,
    order: 49,
  },
  {
    id: 'Q50',
    code: 'Q50',
    domain: 'maturity',
    category: 'maturity.awareness_human',
    answerType: 'yes_no',
    text: {
      ro: 'Sunt efectuate simulări de phishing sau alte teste practice de awareness?',
      en: 'Are phishing simulations or other practical awareness tests performed?',
    },
    weightPoints: 1,
    order: 50,
  },
  {
    id: 'Q51',
    code: 'Q51',
    domain: 'maturity',
    category: 'maturity.awareness_human',
    answerType: 'yes_no',
    text: {
      ro: 'Angajații sunt informați specific despre riscuri precum ransomware și phishing relevante pentru organizație?',
      en: 'Are employees specifically informed about risks like ransomware and phishing relevant to the organization?',
    },
    weightPoints: 0, // punctat doar dacă există instruire
    order: 51,
    scoringInclusionRule: 'G9 == yes',
  },
  {
    id: 'Q52',
    code: 'Q52',
    domain: 'maturity',
    category: 'maturity.awareness_human',
    answerType: 'yes_no',
    text: {
      ro: 'Accesul la date sensibile este acordat doar personalului instruit/briefed pentru acest tip de date?',
      en: 'Is access to sensitive data granted only to personnel trained/briefed for this data type?',
    },
    weightPoints: 0, // informativ
    order: 52,
  },
  // RISC - Furnizori Terți și Cloud
  {
    id: 'Q53',
    code: 'Q53',
    domain: 'risk',
    category: 'risk.third_party_cloud',
    answerType: 'yes_no',
    text: {
      ro: 'Există furnizori terți cu acces la sistemele sau datele companiei?',
      en: 'Are there third-party vendors with access to company systems or data?',
    },
    weightPoints: 0, // gate de diagnostic
    order: 53,
  },
  {
    id: 'Q54',
    code: 'Q54',
    domain: 'risk',
    category: 'risk.third_party_cloud',
    answerType: 'scale',
    text: {
      ro: 'Există cerințe minime de securitate pentru furnizori (contractuale sau operaționale)?',
      en: 'Are there minimum security requirements for vendors (contractual or operational)?',
    },
    weightPoints: 1,
    order: 54,
  },
  {
    id: 'Q55',
    code: 'Q55',
    domain: 'risk',
    category: 'risk.third_party_cloud',
    answerType: 'scale',
    text: {
      ro: 'Accesul furnizorilor este limitat, monitorizat și revocat când nu mai este necesar?',
      en: 'Is vendor access limited, monitored, and revoked when no longer needed?',
    },
    weightPoints: 1,
    order: 55,
  },
  {
    id: 'Q56',
    code: 'Q56',
    domain: 'risk',
    category: 'risk.third_party_cloud',
    answerType: 'yes_no',
    text: {
      ro: 'Furnizorii notifică organizația în caz de incident care ar putea afecta serviciile/datele?',
      en: 'Do vendors notify the organization in case of an incident that could affect services/data?',
    },
    weightPoints: 1,
    order: 56,
  },
  {
    id: 'Q57',
    code: 'Q57',
    domain: 'risk',
    category: 'risk.third_party_cloud',
    answerType: 'scale',
    text: {
      ro: 'Pentru serviciile cloud, sunt activate setări minime de securitate (MFA, logging, secure defaults)?',
      en: 'For cloud services, are minimum security settings enabled (MFA, logging, secure defaults)?',
    },
    weightPoints: 1,
    order: 57,
  },
  {
    id: 'Q58',
    code: 'Q58',
    domain: 'risk',
    category: 'risk.third_party_cloud',
    answerType: 'yes_no',
    text: {
      ro: 'Contractele cu furnizorii includ clauze de securitate IT (acces, incidente, date)?',
      en: 'Do vendor contracts include IT security clauses (access, incidents, data)?',
    },
    weightPoints: 1,
    order: 58,
  },
  {
    id: 'Q59',
    code: 'Q59',
    domain: 'maturity',
    category: 'maturity.asset_visibility',
    answerType: 'yes_no',
    text: {
      ro: 'Există o listă a furnizorilor critici din punct de vedere IT/cyber?',
      en: 'Is there a list of IT/cyber critical vendors?',
    },
    weightPoints: 0, // informativ
    order: 59,
  },
  {
    id: 'Q60',
    code: 'Q60',
    domain: 'risk',
    category: 'risk.third_party_cloud',
    answerType: 'scale',
    text: {
      ro: 'Accesul API / integrările externe sunt controlate și revizuite periodic?',
      en: 'Are API access / external integrations controlled and periodically reviewed?',
    },
    weightPoints: 0, // punctat doar când integrările/cloud-ul sunt relevante
    order: 60,
    scoringInclusionRule: 'G10 == yes || G11 == yes',
  },
];

export const getQuestionById = (id: string): Question | undefined => {
  return questions.find(q => q.id === id || q.code === id);
};

export const getQuestionsInOrder = (): Question[] => {
  return [...questions].sort((a, b) => a.order - b.order);
};

export const getQuestionsByCategory = (category: string): Question[] => {
  return questions.filter(q => q.category === category);
};
