#!/bin/bash
echo "=== CyberXscore Production Secrets Generator ==="
echo ""
echo "JWT_SECRET:"
node -e "console.log(require('crypto').randomBytes(64).toString('hex'))"
echo ""
echo "ANONYMOUS_JWT_SECRET:"
node -e "console.log(require('crypto').randomBytes(64).toString('hex'))"
echo ""
echo "DB_PASSWORD:"
node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"
echo ""
echo "Copy these values into your .env.production file."
echo "Do NOT commit .env.production to git."
